import type { LandingPageData } from "@/features/landing/types/landing";

export const LANDING_PAGE_CONTENT: LandingPageData = {
  header: {
    brand: {
      label: "RedView",
      href: "/",
      logoSrc: "/landing/header/redview-logo.png",
    },
    navigation: [
      {
        id: "fonctionnalites",
        label: "Fonctionnalités",
        href: "#fonctionnalites",
      },
      {
        id: "offres",
        label: "Offres",
        href: "#offres",
      },
      {
        id: "apropos",
        label: "À propos",
        href: "#apropos",
      },
      {
        id: "feedbacks",
        label: "Feedbacks",
        href: "#feedbacks",
      },
    ],
    actions: [
      {
        label: "Voir les offres",
        href: "/pricing",
        variant: "ghost",
      },
      {
        label: "Utiliser RedView",
        href: "/auth/signup",
        variant: "primary",
      },
    ],
  },
  hero: {
    badge: "RedView.app - Advanced Planification Tool (Cycling)",
    headline: {
      prefix: "Enlarge your",
      emphasis: "vision",
    },
    imageSrc: "/landing/hero/backgroud_and_ipad.png",
  },
  featureTiles: [
    {
      id: "cartographie-3d",
      title: "Cartographie 3D haute fidélité",
      titleLines: ["Cartographie 3D", "haute fidélité"],
      icon: "diamond",
      background:
        "linear-gradient(90deg, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.5) 100%), linear-gradient(90deg, rgba(227, 199, 56, 0.52) 0%, rgba(227, 199, 56, 0.52) 100%)",
      widthPx: 325,
      textWidthPx: 301,
    },
    {
      id: "lidar",
      title: "Analyse LIDAR 20cm",
      titleLines: ["Analyse", "LIDAR 20cm"],
      icon: "database",
      background: "rgba(102, 102, 102, 0.6)",
      widthPx: 240,
    },
    {
      id: "pentes",
      title: "Analyse des pentes",
      titleLines: ["Analyse", "des pentes"],
      icon: "arrow-up-right",
      background: "rgba(92, 98, 50, 0.6)",
      widthPx: 240,
    },
    {
      id: "altitude",
      title: "Analyse de l’altitude",
      titleLines: ["Analyse", "de l’altitude"],
      icon: "layers",
      background: "rgba(63, 86, 55, 0.6)",
      widthPx: 240,
    },
    {
      id: "ensoleillement",
      title: "Simulation ensoleillement",
      titleLines: ["Simulation", "ensoleillement"],
      icon: "sun",
      background: "rgba(90, 115, 81, 0.6)",
      widthPx: 240,
    },
    {
      id: "meteo",
      title: "Prévisions et tendances Météo",
      titleLines: ["Prévisions et", "tendances Météo"],
      icon: "cloud-sun",
      background: "rgba(100, 199, 241, 0.4)",
      widthPx: 271,
    },
    {
      id: "vent",
      title: "Vent en temps réel",
      titleLines: ["Vent en temps réel"],
      icon: "wind",
      background: "rgba(63, 151, 234, 0.4)",
      widthPx: 240,
      textWidthPx: 165,
    },
    {
      id: "neige",
      title: "Simulation de la neige en temps réel",
      titleLines: ["Simulation de la", "neige en temps réel"],
      icon: "snowflake",
      background: "rgba(40, 105, 208, 0.4)",
      widthPx: 325,
      textWidthPx: 301,
    },
    {
      id: "itineraire",
      title: "Création d’itinéraire customisable",
      titleLines: ["Création d’itinéraire", "customisable"],
      icon: "sliders",
      background: "rgba(46, 48, 198, 0.39)",
      widthPx: 325,
      textWidthPx: 301,
    },
    {
      id: "comparaison",
      title: "Comparaison d’itinéraire",
      titleLines: ["Comparaison", "d’itinéraire"],
      icon: "route",
      background: "rgba(25, 116, 111, 0.5)",
      widthPx: 240,
    },
    {
      id: "poi",
      title: "Sélection et édition des points d’intérêts (POI)",
      titleLines: ["Sélection et édition des", "points d’intérêts (POI)"],
      icon: "pin",
      background: "rgba(82, 129, 112, 0.6)",
      widthPx: 361,
      textWidthPx: 301,
    },
    {
      id: "rythme",
      title: "Estimation du rythme et gestion des pauses",
      titleLines: ["Estimation du rythme", "et gestion des pauses"],
      icon: "timer",
      background: "rgba(94, 152, 102, 0.6)",
      widthPx: 334,
      textWidthPx: 205,
    },
    {
      id: "timeline",
      title: "Feuille de route et timeline exportables",
      titleLines: ["Feuille de route et", "timeline exportables"],
      icon: "layout",
      background: "rgba(141, 84, 45, 0.6)",
      widthPx: 325,
      textWidthPx: 301,
    },
    {
      id: "graphique",
      title: "Graphique customisable",
      titleLines: ["Graphique", "customisable"],
      icon: "chart",
      background: "rgba(207, 97, 54, 0.5)",
      widthPx: 240,
    },
    {
      id: "projets",
      title: "Gestionnaire de projet",
      titleLines: ["Gestionnaire", "de projet"],
      icon: "folder-check",
      background: "rgba(182, 123, 40, 0.6)",
      widthPx: 240,
    },
  ],
};